# Generated by Django 6.0.7 on 2026-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='color',
            field=models.CharField(default='bg-teal', max_length=20),
        ),
    ]
