# Generated by Django 6.0.7 on 2026-07-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='goal_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.goalcontribution'),
        ),
    ]
